"""
Load and validate the PaySim transaction dataset.

Expects a CSV with the standard PaySim schema (see
https://www.kaggle.com/datasets/ealaxi/paysim1):

    step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig,
    nameDest, oldbalanceDest, newbalanceDest, isFraud, isFlaggedFraud
"""

import pathlib

import pandas as pd

REQUIRED_COLUMNS = [
    "step",
    "type",
    "amount",
    "nameOrig",
    "oldbalanceOrg",
    "newbalanceOrig",
    "nameDest",
    "oldbalanceDest",
    "newbalanceDest",
    "isFraud",
    "isFlaggedFraud",
]

DEFAULT_RAW_PATH = pathlib.Path(__file__).resolve().parents[2] / "data" / "raw"


def load_paysim(path: str | pathlib.Path | None = None) -> pd.DataFrame:
    """
    Load a PaySim-schema CSV into a DataFrame and validate its columns.

    Parameters
    ----------
    path : str or Path, optional
        Path to a specific CSV. If not given, looks for the real dataset
        (PS_*.csv) in data/raw/, then falls back to the synthetic
        sample_paysim.csv generated by src/data/generate_sample.py.

    Raises
    ------
    FileNotFoundError
        If no PaySim CSV can be found.
    ValueError
        If the file is found but missing expected columns.
    """
    if path is None:
        path = _resolve_default_path()
    path = pathlib.Path(path)

    if not path.exists():
        raise FileNotFoundError(
            f"No PaySim data found at {path}. Download the real dataset from "
            "https://www.kaggle.com/datasets/ealaxi/paysim1 and place the CSV "
            "in data/raw/, or run `python -m src.data.generate_sample` to "
            "create a small synthetic sample for pipeline development."
        )

    df = pd.read_csv(path)
    missing = set(REQUIRED_COLUMNS) - set(df.columns)
    if missing:
        raise ValueError(f"{path} is missing expected PaySim columns: {sorted(missing)}")

    return df


def _resolve_default_path() -> pathlib.Path:
    candidates = sorted(DEFAULT_RAW_PATH.glob("PS_*.csv"))
    if candidates:
        return candidates[0]
    return DEFAULT_RAW_PATH / "sample_paysim.csv"


def summarize(df: pd.DataFrame) -> dict:
    """Return a small dict of headline stats used in EDA and sanity checks."""
    return {
        "n_rows": len(df),
        "n_steps": df["step"].nunique(),
        "fraud_rate": df["isFraud"].mean(),
        "n_fraud": int(df["isFraud"].sum()),
        "transaction_types": df["type"].value_counts().to_dict(),
    }


if __name__ == "__main__":
    data = load_paysim()
    for key, value in summarize(data).items():
        print(f"{key}: {value}")
